services:
  manager:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - app_data:/var/www/html/public/uploads
    container_name: user_manager
    networks:
      - mynetwork

  waha:
    image: devlikeapro/waha
    container_name: waha-monitoring
    ports:
      - "3001:3001"
    stdin_open: true  # Habilita interação com o terminal (equivalente a -it)
    tty: true  # Habilita o terminal para o contêiner
    environment:
      - WHATSAPP_API_PORT=3001
      - WHATSAPP_DEFAULT_ENGINE=WEBJS
    volumes:
      - waha_data:/data
    networks:
      - mynetwork

  redis_monitor:
    image: redis:latest
    container_name: bott_redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork

volumes:
  app_data:
  waha_data:

networks:
  mynetwork:
