services:
  manager:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - app_data:/var/www/html/public/uploads
    container_name: user_manager

  waha:
    image: devlikeapro/waha
    container_name: waha-monitoring
    ports:
      - "3001:3001"
    stdin_open: true  # Habilita interação com o terminal (equivalente a -it)
    tty: true  # Habilita o terminal para o contêiner
    environment:
      - WHATSAPP_API_PORT=3001
    volumes:
      - waha_data:/data 

volumes:
  app_data:
  waha_data:
